version: '3'

services:
    db:
        image: mysql:5.7
        volumes:
            - database:/var/lib/mysql
            - ./config/start.sql:/docker-entrypoint-initdb.d/start.sql
            - ./config/eve_universe.sql:/docker-entrypoint-initdb.d/eve_universe.sql
        restart: always
        environment:
          MYSQL_ROOT_PASSWORD: ${MYSQL_PASSWORD}

    pathfinder:
        # build:
        #   context: .
        #   dockerfile: Dockerfile
        restart: always
        image: count20/pathfinder:latest
        env_file: .env
        ports:
            - "8000:80"
            - "8020:8020" 

volumes:
    database: {}
